/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _32 from "./Cw20Stake.types";
import * as _33 from "./Cw20Stake.client";
export namespace contracts {
  export const Cw20Stake = { ..._32,
    ..._33
  };
}