/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CwAdminFactory.types";
import * as _1 from "./CwAdminFactory.client";
export namespace contracts {
  export const CwAdminFactory = { ..._0,
    ..._1
  };
}