/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _22 from "./DaoVotingNativeStaked.types";
import * as _23 from "./DaoVotingNativeStaked.client";
export namespace contracts {
  export const DaoVotingNativeStaked = { ..._22,
    ..._23
  };
}