[package]
name = "cw-snapshot-vector-map"
authors = ["noah <noah@daodao.zone>"]
description = "A CosmWasm vector map that allows reading the items that existed at any height in the past."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
