/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _16 from "./DaoPreProposeSingle.types";
import * as _17 from "./DaoPreProposeSingle.client";
export namespace contracts {
  export const DaoPreProposeSingle = { ..._16,
    ..._17
  };
}