/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _24 from "./CwFundDistributor.types";
import * as _25 from "./CwFundDistributor.client";
export namespace contracts {
  export const CwFundDistributor = { ..._24,
    ..._25
  };
}