/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _6 from "./Cw20StakeExternalRewards.types";
import * as _7 from "./Cw20StakeExternalRewards.client";
export namespace contracts {
  export const Cw20StakeExternalRewards = { ..._6,
    ..._7
  };
}