/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _24 from "./CwdProposalMultiple.types";
import * as _25 from "./CwdProposalMultiple.client";
export namespace contracts {
  export const CwdProposalMultiple = { ..._24,
    ..._25
  };
}