/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _14 from "./CwdVotingStakingDenomStaked.types";
import * as _15 from "./CwdVotingStakingDenomStaked.client";
export namespace contracts {
  export const CwdVotingStakingDenomStaked = { ..._14,
    ..._15
  };
}