/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _8 from "./CwdPreProposeMultiple.types";
import * as _9 from "./CwdPreProposeMultiple.client";
export namespace contracts {
  export const CwdPreProposeMultiple = { ..._8,
    ..._9
  };
}