/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _10 from "./CwdVotingCw4.types";
import * as _11 from "./CwdVotingCw4.client";
export namespace contracts {
  export const CwdVotingCw4 = { ..._10,
    ..._11
  };
}