/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _26 from "./CwdVotingCw20Staked.types";
import * as _27 from "./CwdVotingCw20Staked.client";
export namespace contracts {
  export const CwdVotingCw20Staked = { ..._26,
    ..._27
  };
}