/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _12 from "./DaoPreProposeApprover.types";
import * as _13 from "./DaoPreProposeApprover.client";
export namespace contracts {
  export const DaoPreProposeApprover = { ..._12, ..._13 };
}
