[package]
name = "dao-proposal-single"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "A DAO DAO proposal module for single choice (yes / no) voting."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3"] }
cosmwasm-schema = { workspace = true }
cw-hooks = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
dao-dao-macros = { workspace = true }
dao-hooks = { workspace = true }
dao-interface = { workspace = true }
dao-pre-propose-base = { workspace = true }
dao-voting = { workspace = true }
thiserror = { workspace = true }

cw-utils-v1 = { workspace = true }
voting-v1 = { workspace = true }
cw-proposal-single-v1 = { workspace = true, features = ["library"] }
cw-orch = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-multi-test = { workspace = true }
dao-dao-core = { workspace = true }
dao-voting-cw4 = { workspace = true }
dao-voting-cw20-balance = { workspace = true }
dao-voting-cw20-staked = { workspace = true }
dao-voting-token-staked = { workspace = true }
dao-voting-cw721-staked = { workspace = true }
dao-pre-propose-single = { workspace = true }
cw-denom = { workspace = true }
dao-testing = { workspace = true }
cw20-stake = { workspace = true }
cw20-base = { workspace = true }
cw721-base = { workspace = true }
cw4 = { workspace = true }
cw4-group = { workspace = true }
cw-core-v1 = { workspace = true, features = ["library"] }
