/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _18 from "./DaoVotingStakingDenomStaked.types";
import * as _19 from "./DaoVotingStakingDenomStaked.client";
export namespace contracts {
  export const DaoVotingStakingDenomStaked = { ..._18,
    ..._19
  };
}