/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _20 from "./DaoVotingCw721Staked.types";
import * as _21 from "./DaoVotingCw721Staked.client";
export namespace contracts {
  export const DaoVotingCw721Staked = { ..._20,
    ..._21
  };
}