/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./TokenfactoryIssuer.client";
export declare namespace contracts {
    const TokenfactoryIssuer: {
        TokenfactoryIssuerQueryClient: typeof _1.TokenfactoryIssuerQueryClient;
        TokenfactoryIssuerClient: typeof _1.TokenfactoryIssuerClient;
    };
}
//# sourceMappingURL=index.d.ts.map