/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _30 from "./CwdProposalSingle.types";
import * as _31 from "./CwdProposalSingle.client";
export namespace contracts {
  export const CwdProposalSingle = { ..._30,
    ..._31
  };
}