/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _34 from "./DaoMigrator.types";
import * as _35 from "./DaoMigrator.client";
export namespace contracts {
  export const DaoMigrator = { ..._34,
    ..._35
  };
}