[package]
name = "dao-test-custom-factory"
authors = ["Jake Hartnell"]
description = "A test contract for testing factory patterns in dao-voting-token-staked and dao-voting-cw721-staked."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["osmosis_tokenfactory"]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cw-multi-test/backtrace"]
# use library feature to disable all instantiate/execute/query exports
library = []
# different tokenfactory cosmos sdk module standards. enable corresponding
# standard in types library
osmosis_tokenfactory = ["cw-tokenfactory-issuer/osmosis_tokenfactory"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw2 = { workspace = true }
cw721 = { workspace = true }
cw721-base = { workspace = true, features = ["library"] }
cw-ownable = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils = { workspace = true }
cw-reply-compat = { workspace = true }
thiserror = { workspace = true }
dao-dao-macros = { workspace = true }
dao-interface = { workspace = true }
dao-voting = { workspace = true }
cw-tokenfactory-issuer = { workspace = true, default-features = false, features = [
  "library",
] }

[dev-dependencies]
cw-multi-test = { workspace = true }
