name: Release contracts

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - ci/release-contracts

jobs:
  release:
    runs-on: ubuntu-latest
    container: cosmwasm/workspace-optimizer:0.14.0
    steps:
      - uses: actions/checkout@v3

      # tar is required for cargo cache
      - run: apk add --no-cache tar

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Compile contracts
        timeout-minutes: 30
        run: optimize_workspace.sh .

      - name: Upload contracts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: artifacts/

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
