/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _38 from "./DaoCore.types";
import * as _39 from "./DaoCore.client";
export namespace contracts {
  export const DaoCore = { ..._38,
    ..._39
  };
}