/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _36 from "./DaoCore.types";
import * as _37 from "./DaoCore.client";
export namespace contracts {
  export const DaoCore = { ..._36,
    ..._37
  };
}